/** Slugs con narración TTS en public/audio/<slug>.mp3
 *  Solo audios con resumen publicado (ignora previews/samples).
 */
export const BOOKS_WITH_AUDIO = new Set<string>([
  '21-lessons',
  'ageless',
  'ai-2041',
  'alignment-problem',
  'beginning-of-infinity',
  'being-you',
  'biggest-ideas-universe',
  'biosignatures-astrobiology',
  'black-swan',
  'blind-watchmaker',
  'case-against-reality',
  'consciousness-explained',
  'cosmos',
  'darwins-dangerous-idea',
  'death',
  'determined',
  'eerie-silence',
  'ego-tunnel',
  'el-gran-diseno',
  'elegant-universe',
  'emergent-multiverse',
  'emperors-new-mind',
  'experience-machine',
  'fabric-of-reality',
  'first-three-minutes',
  'free-will',
  'future-of-the-mind',
  'godel-escher-bach',
  'guns-germs-and-steel',
  'hidden-reality',
  'homo-deus',
  'how-we-learn',
  'human-compatible',
  'incognito',
  'intelligent-life-universe',
  'life-3-0',
  'lifespan',
  'livewired',
  'murmurs-of-earth',
  'order-of-time',
  'origins',
  'otherlands',
  'our-mathematical-universe',
  'quantum-enigma',
  'reality-not-what-it-seems',
  'sapiens',
  'self-assembling-brain',
  'selfish-gene',
  'seven-brief-lessons',
  'something-deeply-hidden',
  'structure-scientific-revolutions',
  'superintelligence',
  'the-brain',
  'the-gene',
  'the-information',
  'thinking-fast-and-slow',
  'universo-de-la-nada',
  'vital-question',
  'what-is-life',
  'why-does-world-exist',
  'why-evolution-is-true',
  'why-we-die',
  'wonderful-life',
])

export function bookHasAudio(slug: string): boolean {
  return BOOKS_WITH_AUDIO.has(slug)
}

